githubConfigUrl: https://github.com/rivasjp/gitops
githubConfigSecret: github-pat

controllerServiceAccount:
  name: arc-gha-rs-controller
  namespace: arc-systems

minRunners: 0
maxRunners: 2

template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 1Gi
