# Workloads: consumers of what the addons install.
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workloads
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  enable_workloads: "true"
          - git:
              repoURL: https://github.com/rivasjp/gitops
              revision: main
              directories:
                - path: workloads/*/*
  template:
    metadata:
      name: '{{.path.basename}}-{{.name}}'
    spec:
      project: default
      source:
        repoURL: '{{.metadata.annotations.gitops_repo_url}}'
        targetRevision: '{{.metadata.annotations.gitops_repo_revision}}'
        path: '{{.path.path}}'
      destination:
        name: '{{.name}}'
        namespace: arc-runners
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
