apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: configs
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/rivasjp/gitops
              revision: main
              directories:
                - path: 'environments/*/configs/*'
          - clusters:
              selector:
                matchLabels:
                  environment: '{{index .path.segments 1}}'
  template:
    metadata:
      name: 'config-{{.name}}-{{.path.basename}}'
    spec:
      project: default
      source:
        repoURL: '{{.metadata.annotations.gitops_repo_url}}'
        targetRevision: '{{.metadata.annotations.gitops_repo_revision}}'
        path: '{{.path.path}}'
      destination:
        name: '{{.name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
